package carlosguso.ejercicio.model;
// Generated 29-oct-2019 14:27:56 by Hibernate Tools 4.3.1



/**
 * AlumnosMaterias generated by hbm2java
 */
public class AlumnosMaterias  implements java.io.Serializable {


     private AlumnosMateriasId id;

    public AlumnosMaterias() {
    }

    public AlumnosMaterias(AlumnosMateriasId id) {
       this.id = id;
    }
   
    public AlumnosMateriasId getId() {
        return this.id;
    }
    
    public void setId(AlumnosMateriasId id) {
        this.id = id;
    }




}


