package carlosguso.ejercicio.model;
// Generated 29-oct-2019 14:27:56 by Hibernate Tools 4.3.1



/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private int identificador;
     private String nombre;
     private String sexo;
     private Integer edad;

    public Alumnos() {
    }

	
    public Alumnos(int identificador) {
        this.identificador = identificador;
    }
    public Alumnos(int identificador, String nombre, String sexo, Integer edad) {
       this.identificador = identificador;
       this.nombre = nombre;
       this.sexo = sexo;
       this.edad = edad;
    }
   
    public int getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(int identificador) {
        this.identificador = identificador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }




}


