package carlosguso.ejercicio.model;
// Generated 29-oct-2019 14:27:56 by Hibernate Tools 4.3.1



/**
 * Materias generated by hbm2java
 */
public class Materias  implements java.io.Serializable {


     private int identificador;
     private Profesores profesores;
     private String nombre;

    public Materias() {
    }

	
    public Materias(int identificador) {
        this.identificador = identificador;
    }
    public Materias(int identificador, Profesores profesores, String nombre) {
       this.identificador = identificador;
       this.profesores = profesores;
       this.nombre = nombre;
    }
   
    public int getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(int identificador) {
        this.identificador = identificador;
    }
    public Profesores getProfesores() {
        return this.profesores;
    }
    
    public void setProfesores(Profesores profesores) {
        this.profesores = profesores;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


